language: node_js
node_js:
- node
before_deploy:
- npm run build:prod
deploy:
  # add this line after travis setup
  skip_cleanup: true
  provider: npm
  email: Bengejdb@gmail.com
  api_key:
    secure: "AUboMoBSRiEp9ILxknDPqoxfw8BSkLRx/rcMi+NQEQpB31Rqdd2MkEPOTJ2pa/V/XLbhbOoMKxc9SnWWihON0w9p45DKk0UdSFKgvLnAE8dUXvM1nXxyNB3A3awCsiWF/GoHFjyuXxW/UyyN+v3f3biMorb7sJ6J5ph7imiXwIEJKYYQYc0bwZFyeCK3QX+IRQmtzZRm4a+OZQBqzgYdY/iIOvMdAdwZoRmOUVDQ+BynBM2iZxwMjoxswRgj4QFlfasBS+f/0Zh9wOKCAogg+1qOooasvFzNYFtnWtqx6CH9F0uo+7Ilw/CK++URI1XHR8V5+Q0ZnPokG94Y0gQ4x7IaZByHSO602Byxuh81SY87uT9XYHFX6LAfBQFxB7AUQYosakmpuQ8F+TLrsLoplb777M3Ohom/CDiLCiGcIx0Tl7R0XnAUNHjuAwWMX0zLVR4g1LAE4Ug4VgebLf+wO58ywoUqET9ANad97Z4T49h0R5m6GVq+ivmNE5zL0UhkFLODpJIpBPz4+QIxQXvzEbKSwDsUl96GcgkYckWsSfoDHEEPjQCM/gViVA/QP6pV9ZA+WecA/AqwMNbyOUse7bh0ChyqY566ND9dEYWWxrC4phcuScihDKvpAEs2+Wpo/slJq/Xa4W9FSydv/cepu4YslF+wRgA780BIG8WKa3I="
  on:
    tags: true
    repo: Bengejd/NOLS
