language: node_js
node_js:
- node
before_deploy:
- npm run build:prod
deploy:
  skip_cleanup: true
  provider: npm
  email: Bengejdb@gmail.com
  api_key:
    secure: gB/UlAvQWgfafMvMCrAaG0irrTe7Z7rrnlKUYYksV5hEEM0/CsxHvAKt6lotdO2BFw08Qp9QSCUMyS1nSJouw1KLZ6Hed9LaQZzzlNiD2kdcRmnUfDH81XmDnuC2nhKMo/KoM5XOhcLyX2XfnTwW3++GB987rvW9ayvqLjxWAD8RKg3wPQ6JWaHMOAZVVyZ860JAk43N6j7hklNXqEX9H027Z3g9wHR8ad4Y3iK4qjMiiNP3I7jK1Z4ltyjIPTpDRLzxaCfkJ16zZ8YQ+e4Kpj3BSrmEJq+XZ64bukmsYsfbemiN57DsBeDZSMk/SsZPL5vorPTr9nIEj1xjGWUrrKhnuDP4lp4DatRvN7Uc45trXdoktHlhBExyBHQxjUe4UwEyV8//mzyYnexqh4Hw5xzwW+INRSIAMLoGmjD2Rv//Oz0xCoVrFh03wDVwrSguowF1xUeYhJ40nxXdtEBNztiRWSiICKZDYJFQeFTVOBhELVfyN67VZ3oAGGCmpc2k+NuDEtRSaPmPQ7vtdeZ+pqzu8lQqUF2onrTfhD8MB2ghjT8M6RcdheJNkeulR4Ti0TlUhRCYPOvVa7e0hLEXudyW8gv6zthiHKcBIKWHJk3fldhZQOnk3tfIBeYUHi/C1GdyACvnQeNKfxcfSXStpS+7zSHQxIkRZs+Z4bdpc8s=
  on:
    tags: true
    repo: Bengejd/NOLS
